name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.cfg.os }}, 🐍=${{ matrix.cfg.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - conda-env: env
            python-version: 3.11
            os: ubuntu-latest

          - conda-env: env
            python-version: 3.11
            os: macOS-latest

    env:
      CI_OS: ${{ matrix.cfg.os }}
      ENV: ${{ matrix.cfg.conda-env }}
      PYVER: ${{ matrix.cfg.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Create Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/${{ matrix.cfg.conda-env }}.yaml
          create-args: python=${{ matrix.python-version }}

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info
          conda list --show-channel-urls

      - name: Install NAGL-MBIS
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: PyTest
        shell: bash -l {0}
        run: |
          pytest -v --cov=naglmbis --cov-config=setup.cfg naglmbis/tests/ --cov-report=xml --color=yes

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: false