name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create Environment
        shell: bash
        run: |
          pip install -e . --no-build-isolation 

      - name: Install black
        shell: bash
        run: |
          pip install black

      - name: Run black
        shell: bash
        run: |
          black naglmbis --check