name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install lint
        shell: bash
        run: |
          pip install black isort flake8

      - name: Run black
        shell: bash
        run: |
          black naglmbis --check

      - name: Run isort
        shell: bash
        run: |
          isort --check-only naglmbis

      - name: Run flake8
        shell: bash
        run: |
          flake8 naglmbis